server:
  port: 8003
spring:
  application:
    name: eureka-server3
eureka:
  instance:
    hostname: eureka-server3 #Eureka实例的主机名
  client:
    fetch-registry: false #不向注册中心注册自己
    register-with-eureka: false #是否检索服务
    serviceUrl:
      defaultZone: http://eureka1.ratel.com:8001/eureka/,http://eureka2.ratel.com:8002/eureka/ #Eureka 注册中心地址

